name: INTEGRAÇÃO CONTINUA

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Inicia banco de dados 
      run: docker compose up -d postgres

    - name: Verifica conexão com PostgreSQL
      run: |
        echo "Verificando conexão com PostgreSQL..."
        PGPASSWORD=${{ secrets.DB_PASSWORD }} pg_isready -h localhost -U ${{ secrets.DB_USER }} -d ${{ secrets.DB_NAME }} -p 5432
        echo "Conexão bem-sucedida!"

    - name: Testa a aplicação
      env:
        DB_HOST: localhost
        DB_USER: ${{ secrets.DB_USER }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        DB_NAME: ${{ secrets.DB_NAME }}
        DB_PORT: 5432
      run: go test -v main_test.go