name: INTEGRAÇÃO CONTINUA

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Inicia banco de dados 
      run: docker compose up -d postgres

    - name: Verifica conexão com PostgreSQL
      run: |
        echo "Verificando conexão com PostgreSQL..."
        for i in {1..10}; do
          if PGPASSWORD=root pg_isready -h localhost -U root -d root -p 5432; then
            echo "Conexão bem-sucedida!"
            exit 0
          fi
          echo "Tentativa $i: PostgreSQL não está pronto. Aguardando..."
          sleep 3
        done
        echo "Erro: PostgreSQL não está respondendo após 10 tentativas."
        exit 1

    - name: Testa a aplicação
      env:
        DB_HOST: ${{ secrets.DB_HOST }}
        DB_USER: root
        DB_PASSWORD: root
        DB_NAME: root
        DB_PORT: 5432
      run: go test -v main_test.go