name: INTEGRAÇÃO CONTINUA

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Inicia banco de dados 
      run: docker compose up -d postgres

    - name: Espera PostgreSQL ficar pronto
      run: |
        for i in {1..10}; do
          if pg_isready -h localhost -U ${{ secrets.DB_USER }} -d ${{ secrets.DB_NAME }} -p 5432; then
            echo "PostgreSQL está pronto!"
            break
          fi
          echo "Esperando PostgreSQL ficar pronto..."
          sleep 3
        done

    - name: Lint 
      uses: golangci/golangci-lint-action@v6
      with:
        version: v1.64
        args: controllers/ database/ models/ routes/

    - name: Testa a aplicação
      env:
        DB_HOST: ${{ secrets.DB_HOST }}
        DB_USER: ${{ secrets.DB_USER }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        DB_NAME: ${{ secrets.DB_NAME }}
        DB_PORT: ${{ secrets.DB_PORT }}
      run: go test -v ./...